### ISSUE TITLE
Ajude a localizar! - The Web Is a Tool for Learning

### ISSUE THREAD

**Issue by barrosgg** [mozillabrasil/mozteach-wlbtwo#1]
Localize esta atividade no HTML [_session02-the-web-is-a-tool-for-learning.html_](https://github.com/mozillabrasil/mozteach-wlbtwo/blob/gh-pages/session02-the-web-is-a-tool-for-learning.html) e você pode conferir a pagina funcionando em sua respectiva [GitHub Pages](http://mozillabrasil.github.io/mozteach-wlbtwo/session02-the-web-is-a-tool-for-learning.html).

Good work! :dart:

**Comment by Ladeia** [comment]
Eu fico com essa e entrego até o fim de semana

**Comment by barrosgg** [comment]
@Ladeia se precisar de ajuda é só comentar aqui e marcar a Label "PRECISA DE AJUDA", bom trabalho!

**Comment by Ladeia** [comment]
Pessoal desculpem a demora, tive uns problemas em familia, mas envio esse pull request ainda essa semana.

**Comment by barrosgg** [comment]
Ladeia, sem problemas, aguardamos ansiosamente a tradução. :D

**Comment by barrosgg** [comment]
@Ladeia, como está o andamento da tradução? Se precisar de ajuda, por gentileza, adicione a label "Precisa de ajuda".

**Comment by Ladeia** [comment]
opa gente, tinha esquecido, voltei a localização hoje

**Comment by Ladeia** [comment]
traduzidos:
- Introdução
- Preparação
- Faça o Projeto

**Comment by torto** [comment]
Posso ajudar?

**Comment by Ladeia** [comment]
claro @torto, essas ai em cima são as sessões que estão feitas, estão no meu fork, se quiser vc pode mandar pr pra ca ou como achar melhor

**Comment by torto** [comment]
Posso traduzir o 
- Reflexão

Mais como não sou bom em inglês, tu pode revisar legal?

**Comment by Ladeia** [comment]
Perfeito torto, sem probs

Em 26 de ago de 2016 17:01, "Guilherme Costa Berghauser" <
notifications@github.com> escreveu:

**Comment by torto** [comment]
@Ladeia Enviei o PR na tua branch :heart:

**Comment by Ladeia** [comment]
massa, vou aceitar e revisar, acredito que hoje termine a tradução :-)

**Comment by torto** [comment]
@Ladeia estou traduzindo a introdução do #7, assim que terminar e quiser ajudar lá <3

**Comment by Ladeia** [comment]
mandei o pull request, precisa de revisão.
Malzs a demora pessoal.

**Comment by halcance** [comment]
A tradução foi migrada para o Pontoon todos os arquivos serão traduzidos através do mesmo. Agradecemos a contribuição de todos que se manifestaram.

**Comment by Ladeia** [comment]
Não entendi direito, a traduçao será migrada ou será descartada?

**Comment by halcance** [comment]
@Ladeia as traduções agora são feitas pelo Pontoon, todos os sites da mozilla exceto a wiki e o Activate Mozilla são traduzidos manualmente pelos seus desenvolvedores.
