### ISSUE TITLE
Ajude a localizar! - Project Playlist

### ISSUE THREAD

**Issue by barrosgg** [mozillabrasil/mozteach-wlbtwo#2]
Localize esta atividade no HTML [_bridge01-project-playlist.html_](https://github.com/mozillabrasil/mozteach-wlbtwo/blob/gh-pages/bridge01-project-playlist.html) e você pode conferir a pagina funcionando em sua respectiva [GitHub Pages](http://mozillabrasil.github.io/mozteach-wlbtwo/bridge01-project-playlist.html).

Good work! :dart:

**Comment by jppcel** [comment]
Vou fazer esse.

**Comment by barrosgg** [comment]
@jppcel se precisar de ajuda é só comentar aqui e marcar a Label "PRECISA DE AJUDA", bom trabalho!

**Comment by barrosgg** [comment]
@jppcel Revisado! Você fez um grande trabalho, a qualidade da localização/tradução está **ótima**! 

Antes de fechar esta issue eu gostaria de lhe oferecer um voucher em seu [Mozillians](https://mozillians.org) como forma de reconhecer seu trabalho na comunidade, se você desejar, comente com o link do seu perfil.

Abraços,
Geraldo Barros

**Comment by jppcel** [comment]
@barrostecnologia Opa! Obrigado! https://mozillians.org/pt-BR/u/jppcel/

**Comment by barrosgg** [comment]
Voucher adicionado e READ.MD atualizado com o nome e progresso, estou fechando esta.
