### ISSUE TITLE
Ajude a localizar! - Pixel Portrait

### ISSUE THREAD

**Issue by barrosgg** [mozillabrasil/mozteach-wlbtwo#4]
Localize esta atividade no HTML [_bridge02-pixel-portrait.html_](http://mozillabrasil.github.io/mozteach-wlbtwo/bridge02-pixel-portrait.html) e você pode conferir a pagina funcionando em sua respectiva [GitHub Pages](http://mozillabrasil.github.io/mozteach-wlbtwo/bridge02-pixel-portrait.html).

Good work! :dart:

**Comment by ninjacontato** [comment]
vou traduzir @barrostecnologia

**Comment by barrosgg** [comment]
@ninjacontato se precisar de ajuda é só comentar aqui e marcar a Label "PRECISA DE AJUDA", bom trabalho!

**Comment by barrosgg** [comment]
@ninjacontato, como está o andamento da tradução? Se precisar de ajuda, por gentileza, adicione a label "Precisa de ajuda".

**Comment by halcance** [comment]
A tradução foi migrada para o Pontoon todos os arquivos serão traduzidos através do mesmo. Agradecemos a contribuição de todos que se manifestaram.
