### ISSUE TITLE
Ajude a localizar! - #allthestickerz

### ISSUE THREAD

**Issue by barrosgg** [mozillabrasil/mozteach-wlbtwo#5]
Localize esta atividade no HTML [_session04-allthestickerz.html_](https://github.com/mozillabrasil/mozteach-wlbtwo/blob/gh-pages/session04-allthestickerz.html) e você pode conferir a pagina funcionando em sua respectiva [GitHub Pages](http://mozillabrasil.github.io/mozteach-wlbtwo/session04-allthestickerz.html).

Good work! :dart:

**Comment by estherdefreitas** [comment]
Traduzindo o/ @barrostecnologia

**Comment by barrosgg** [comment]
@estherdefreitas se precisar de ajuda é só comentar aqui e marcar a Label "PRECISA DE AJUDA", bom trabalho!

**Comment by barrosgg** [comment]
@estherdefreitas , como está o andamento da tradução? Se precisar de ajuda, por gentileza, adicione a label "Precisa de ajuda".

**Comment by halcance** [comment]
A tradução foi migrada para o Pontoon todos os arquivos serão traduzidos através do mesmo. Agradecemos a contribuição de todos que se manifestaram.
