### ISSUE TITLE
Ajude a localizar! - Who Am I?

### ISSUE THREAD

**Issue by barrosgg** [mozillabrasil/mozteach-wlbtwo#6]
Localize esta atividade no HTML [_bridge03-who-am-i.html_](https://github.com/mozillabrasil/mozteach-wlbtwo/blob/gh-pages/bridge03-who-am-i.html) e você pode conferir a pagina funcionando em sua respectiva [GitHub Pages](http://mozillabrasil.github.io/mozteach-wlbtwo/bridge03-who-am-i.html).

Good work! :dart:

**Comment by thiagopolicena** [comment]
Irei ficar com essa, até o fim de semana termino.

**Comment by barrosgg** [comment]
@thiagopolicena se precisar de ajuda é só comentar aqui e marcar a Label "PRECISA DE AJUDA", bom trabalho!

**Comment by thiagopolicena** [comment]
Feita a localização completa para pt-br, favor verificar se possui algum erro.

**Comment by barrosgg** [comment]
@thiagopolicena @willtrindade, obrigado pela tradução e revisão, por gentileza, me informem o http://mozillians.org de vocês para o voucher. :-)
