### ISSUE TITLE
Ajude a localizar! - Fair Use Free-for-All

### ISSUE THREAD

**Issue by barrosgg** [mozillabrasil/mozteach-wlbtwo#7]
Localize esta atividade no HTML [_session05-fair-use-free-for-all.html_](https://github.com/mozillabrasil/mozteach-wlbtwo/blob/gh-pages/session05-fair-use-free-for-all.html) e você pode conferir a pagina funcionando em sua respectiva [GitHub Pages](http://mozillabrasil.github.io/mozteach-wlbtwo/session05-fair-use-free-for-all.html).

Good work! :dart:

**Comment by torto** [comment]
Posso traduzir esse?

**Comment by barrosgg** [comment]
Yes, of course man!

**Comment by Ladeia** [comment]
Opa @torto ainda está traduzindo?

**Comment by torto** [comment]
@Ladeia parei em uma parte e não tive mais tempo de fazer nada... se quiser tocar manda ver!

**Comment by halcance** [comment]
A tradução foi migrada para o Pontoon todos os arquivos serão traduzidos através do mesmo. Agradecemos a contribuição de todos que se manifestaram.
