### ISSUE TITLE
Ajude a localizar! - The Planets

### ISSUE THREAD

**Issue by barrosgg** [mozillabrasil/mozteach-wlbtwo#8]
Localize esta atividade no HTML [_session06-the-planets-and-accessibility.html_](https://github.com/mozillabrasil/mozteach-wlbtwo/blob/gh-pages/session06-the-planets-and-accessibility.html) e você pode conferir a pagina funcionando em sua respectiva [GitHub Pages](http://mozillabrasil.github.io/mozteach-wlbtwo/session06-the-planets-and-accessibility.html).

Good work! :dart:

**Comment by maribeiromendes** [comment]
@barrostecnologia vou fazer esse :)

**Comment by barrosgg** [comment]
@meldenne se precisar de ajuda é só comentar aqui e marcar a Label "PRECISA DE AJUDA", bom trabalho!

**Comment by halcance** [comment]
Página totalmente traduzida.

Link inválido.

**Comment by halcance** [comment]
Necessita de revisão.

**Comment by barrosgg** [comment]
@alipseight, eu vejo que este não teve a tradução concluída. Se teve, a @meldenne talvez esqueceu de dar o push.

**Comment by halcance** [comment]
Pequenas partes que sairiam do contexto.

**Comment by halcance** [comment]
A tradução foi migrada para o Pontoon todos os arquivos serão traduzidos através do mesmo. Agradecemos a contribuição de todos que se manifestaram.
